# Generated by Django 5.0.1 on 2024-02-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IsaacTool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.DecimalField(decimal_places=10, max_digits=19)),
                ('j', models.DecimalField(decimal_places=10, max_digits=19)),
                ('k', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
