# Generated by Django 5.0.1 on 2024-02-28 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IsaacTool', '0004_vectormodel_delete_vector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
