# Generated by Django 5.0.1 on 2024-02-29 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IsaacTool', '0005_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VectorModel',
        ),
    ]
