# Generated by Django 5.0.1 on 2024-02-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IsaacTool', '0006_delete_vectormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('linear_coefficient', models.DecimalField(decimal_places=10, max_digits=10)),
                ('volumetric_coefficient', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
